# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
print(s.split(' '))

['Hi', 'there', 'Sam!']

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print('The diameter of {}is {} kilometers'.format(planet,diameter));

The diameter of Earthis 12742 kilometers

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d['k1'][3]["tricky"][3]['target'][3])

hello

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [ ]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
array1=np.arange(20,35,2)
print("Array of all the even integers from 30 to 70")
print(array1)

Array of all the even integers from 30 to 70
[20 22 24 26 28 30 32 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

arr = np.concatenate((a, b))

print(arr)

[1 2 3 4 5 6]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [ ]:
# initialize list of lists
data = [['Ram', 30], ['Seeta', 65], ['Lakshmanan', 100],['Bavya',50]]
  
# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['Name', 'Marks'])
  
# print dataframe.
df

         Name  Marks
0         Ram     30
1       Seeta     65
2  Lakshmanan    100
3       Bavya     50

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
pd.date_range('2023-01-01', '2023-02-10', freq='D')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
df = pd.DataFrame(lists, columns =['S.No', 'Letters','Numbers']) 
print(df )

   S.No Letters  Numbers
0     1     aaa       22
1     2     bbb       25
2     3     ccc       24